#!/usr/bin/env bash
#
#filepath: shell/system_toolbox
#email: qyf1009@163.com
#author: qian1009
#date: 2019/10/14
#modify_time: @time
#usage: system manager box

cat <<-EOF
      +-----------------------------+
      |         系统管理工具        |
      +-----------------------------+
      |    a. 显示系统中用户数量    |
      |    2. 显示系统中进程数量    |
      |    3. 退出                  |
      +-----------------------------+
EOF
read -p "请输入所要执行的选项： " choose
case ${choose} in
	a)
		number=$(wc -l /etc/passwd)
		echo "系统中用户数量为 ${number: 0: 3}"
		;;
	2)
		echo "系统中进程数量为 $(ps aux | wc -l)"
		;;
	3)
		exit
		;;
	*)
		echo "请输入正确的选项！"
			
		read -p "请输入所要执行的选项： " choose
		case ${choose} in
		a)
			number=$(wc -l /etc/passwd)
			echo "系统中用户数量为 ${number: 0: 3}"
			;;
		2)
			echo "系统中进程数量为 $(ps aux | wc -l)"
			;;
		3)
			exit
			;;
		*)
			echo "请输入正确的选项！"
			;;
		esac
		;;
	
esac
